typography_spectrum: 0.2365591
color:
  brandColors:
    - '#9a0c0b'
    - '#eb2728'
    - '#fe4646'
    - '#640606'
    - '#b32e2f'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2628
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Andrew Gordon
  email: Andrew@Air-Media.ca
name: The Dev Smith
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Who the hell am I
    id: 239ed26a-9585-4cfb-a37c-705841c5eefa
    type: content
favicon: null
title: Develop Stuff
description: Dev is the Start
purpose: []
