typography_spectrum: 0.2365591
color:
  brandColors:
    - '#9a0c0b'
    - '#eb2728'
    - '#fe4646'
    - '#640606'
    - '#b32e2f'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0.5
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.2628
analytics:
  google: null
  facebook: null
  twitter: null
name: The Dev Smith
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The Dev Smith
description: Dev is the Start
purpose: []
